# Generated by Django 4.0.1 on 2022-02-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaimage',
            name='editable',
        ),
        migrations.AlterField(
            model_name='tablaimage',
            name='format_img',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tablaimage',
            name='name_img',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tablaimage',
            name='url_img',
            field=models.ImageField(blank='', default='', upload_to='img/'),
        ),
    ]
