# Generated by Django 4.0.1 on 2022-02-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_remove_tablaimage_editable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaimage',
            name='editted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
