# Generated by Django 4.0.1 on 2022-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0003_tablaimage_editted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaimage',
            name='url_img',
            field=models.ImageField(blank='', default='', upload_to='assets/img/'),
        ),
    ]
